#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Copyright: 2015 Bastian Blank
# License: MIT, see LICENSE.txt for details.

import os

from azure_manage.cli.build_image import Main


if __name__ == '__main__':
    basedir = os.path.dirname(__file__)
    Main(basedir)()
