#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Copyright: 2015 Bastian Blank
# License: MIT, see LICENSE.txt for details.

import argparse

from azure.servicemanagement.publishsettings import get_certificate_from_publish_settings


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Extract key and certificate from .publishsettings files')
    parser.add_argument('input', metavar='INPUT')
    parser.add_argument('output', metavar='OUTPUT')

    args = parser.parse_args()

    get_certificate_from_publish_settings(args.input, args.output)
